### ISSUE TITLE
User's unable to delete events

### ISSUE THREAD

**Issue by cherukumilli** [hackerdojo/hd-events#101]
Please see the email below from Daniel Watson.

Dojo Events to events
Show more
5:27 PM
Event: why can't i delete events anymore?
Member: daniel.watson@hackerdojo.com
When: 09/03/16 01:00PM to 05:00PM
Repeats: Never
Type: Workshop
Size: 10
Rooms: Classroom
Contact: Daniel Watson (805.699.5690)
URL: challenge-bot.com
Fee: 

Details: delete this event please

Notes: 

http://events.hackerdojo.com/event/5823088826515456-why-can-t-i-delete-events-anymore-

**Comment by cherukumilli** [comment]
@Cealtea 
Did the changes today have anything to with Danny unable to delete his event?

**Comment by Cealtea** [comment]
No I don't think so because I only changed html files and added the refresh
on the main pages. I did not deploy the app since the refresh on the main
page.
-- 
Celine Bursztein
------------------------------------------------------
http://celine.im
@cealtea <https://twitter.com/cealtea> on Twitter, +Celine Bursztein
<https://plus.google.com/+Celine%20Bursztein> on Google+

**Comment by cherukumilli** [comment]
ok.
I will wait to see if anyone else is complaining before closing this issue.
